version: '3.4'

services:
  api_gateway:
    image: api_gateway
    pull_policy: always
    env_file:
      - .env

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    build:
      context: ../
      dockerfile: devops/Dockerfile
    ports:
      # - "#{API_PORT}#:80"
      - "5095:80"
      - "7034:443"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    #   - .aspnet/https:/https/
