apiVersion: v1
kind: Service
metadata:
  name: web-api-test
  labels:
    app: web-api-test
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    nodePort: 31002
  selector:
    app: web-api-test